name: Build bitcoind on arm
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Register self-compiled qemu
        run: docker run --rm --privileged meedamian/simple-qemu-test:minimal --reset -p yes
      - name: Build the Docker image
        run: docker build . --file 0.18/source/Dockerfile --tag bitcoind:arm-$(date +%s)
